import { Profile } from "../profile";

export interface PlayerPlayInfoResponse {
    cabid: KITEM<'s32'>,
    play: KITEM<'s32'>,
    playtime: KITEM<'s32'>,
    playterm: KITEM<'s32'>,
    session_cnt: KITEM<'s32'>,
    matching_num: KITEM<'s32'>,
    extra_stage: KITEM<'s32'>,
    extra_play: KITEM<'s32'>,
    extra_clear: KITEM<'s32'>,
    encore_play: KITEM<'s32'>,
    encore_clear: KITEM<'s32'>,
    pencore_play: KITEM<'s32'>,
    pencore_clear: KITEM<'s32'>,
    max_clear_diff: KITEM<'s32'>,
    max_full_diff: KITEM<'s32'>,
    max_exce_diff: KITEM<'s32'>,
    clear_num: KITEM<'s32'>,
    full_num: KITEM<'s32'>,
    exce_num: KITEM<'s32'>,
    no_num: KITEM<'s32'>,
    e_num: KITEM<'s32'>,
    d_num: KITEM<'s32'>,
    c_num: KITEM<'s32'>,
    b_num: KITEM<'s32'>,
    a_num: KITEM<'s32'>,
    s_num: KITEM<'s32'>,
    ss_num: KITEM<'s32'>,
    last_category: KITEM<'s32'>,
    last_musicid: KITEM<'s32'>,
    last_seq: KITEM<'s32'>,
    disp_level: KITEM<'s32'>,
}
export function getPlayerPlayInfoResponse(profile : Profile) : PlayerPlayInfoResponse {
    return {
        cabid: K.ITEM('s32', 0),
        play: K.ITEM('s32', profile.play),
        playtime: K.ITEM('s32', profile.playtime),
        playterm: K.ITEM('s32', profile.playterm),
        session_cnt: K.ITEM('s32', profile.session_cnt),
        matching_num: K.ITEM('s32', 0),
        extra_stage: K.ITEM('s32', profile.extra_stage),
        extra_play: K.ITEM('s32', profile.extra_play),
        extra_clear: K.ITEM('s32', profile.extra_clear),
        encore_play: K.ITEM('s32', profile.encore_play),
        encore_clear: K.ITEM('s32', profile.encore_clear),
        pencore_play: K.ITEM('s32', profile.pencore_play),
        pencore_clear: K.ITEM('s32', profile.pencore_clear),
        max_clear_diff: K.ITEM('s32', profile.max_clear_diff),
        max_full_diff: K.ITEM('s32', profile.max_full_diff),
        max_exce_diff: K.ITEM('s32', profile.max_exce_diff),
        clear_num: K.ITEM('s32', profile.clear_num),
        full_num: K.ITEM('s32', profile.full_num),
        exce_num: K.ITEM('s32', profile.exce_num),
        no_num: K.ITEM('s32', profile.no_num),
        e_num: K.ITEM('s32', profile.e_num),
        d_num: K.ITEM('s32', profile.d_num),
        c_num: K.ITEM('s32', profile.c_num),
        b_num: K.ITEM('s32', profile.b_num),
        a_num: K.ITEM('s32', profile.a_num),
        s_num: K.ITEM('s32', profile.s_num),
        ss_num: K.ITEM('s32', profile.ss_num),
        last_category: K.ITEM('s32', profile.last_category),
        last_musicid: K.ITEM('s32', profile.last_musicid),
        last_seq: K.ITEM('s32', profile.last_seq),
        disp_level: K.ITEM('s32', profile.disp_level),
      }
}

